import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { resolve } from "path";

const root = resolve(__dirname, "..");
const mockDir = resolve(__dirname, "browser-mocks");

/**
 * Vite plugin that patches bindings.ts to add missing command stubs.
 * bindings.ts is auto-generated by tauri-specta but may be missing commands
 * that the Rust backend defines (e.g., initializeShortcuts).
 */
function patchBindings(): Plugin {
  const bindingsPath = resolve(root, "src/bindings.ts");

  const initializeShortcutsImpl = `,\nasync initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}`;

  return {
    name: "patch-bindings",
    enforce: "pre",
    transform(code, id) {
      if (!id.includes("src/bindings.ts")) return;
      if (code.includes("async initializeShortcuts(")) return;

      // The commands object ends with "}\n}\n\n/** user-defined events **/"
      // We need to insert our new method just before the LAST "}" before the marker.
      // Strategy: find the "}\n}\n\n/** user-defined events" pattern and insert between
      // the two closing braces.
      const patched = code.replace(
        /(\n\}\n)(\}\n\n\/\*\* user-defined events \*\*\/)/,
        `$1${initializeShortcutsImpl}\n$2`,
      );

      if (patched !== code) {
        return { code: patched, map: null };
      }
    },
  };
}

/**
 * E2E Vite config — clones the production config but aliases all @tauri-apps/*
 * and tauri-plugin-* imports to browser-compatible mock modules.
 *
 * Usage: bun run dev:e2e
 * Then navigate to http://localhost:1420 in a browser.
 */
export default defineConfig({
  root,
  plugins: [patchBindings(), react(), tailwindcss()],

  resolve: {
    alias: {
      // Path alias from production config
      "@": resolve(root, "./src"),
      "@/bindings": resolve(root, "./src/bindings.ts"),

      // ── @tauri-apps/api/* ─────────────────────────────────────────
      "@tauri-apps/api/core": resolve(mockDir, "tauri-api-core.ts"),
      "@tauri-apps/api/event": resolve(mockDir, "tauri-api-event.ts"),
      "@tauri-apps/api/window": resolve(mockDir, "tauri-api-window.ts"),
      "@tauri-apps/api/webviewWindow": resolve(mockDir, "tauri-api-webview-window.ts"),
      "@tauri-apps/api/app": resolve(mockDir, "tauri-api-app.ts"),

      // ── @tauri-apps/plugin-* ──────────────────────────────────────
      "@tauri-apps/plugin-os": resolve(mockDir, "tauri-plugin-os.ts"),
      "@tauri-apps/plugin-opener": resolve(mockDir, "tauri-plugin-opener.ts"),
      "@tauri-apps/plugin-clipboard-manager": resolve(mockDir, "tauri-plugin-clipboard.ts"),
      "@tauri-apps/plugin-store": resolve(mockDir, "tauri-plugin-store.ts"),
      "@tauri-apps/plugin-autostart": resolve(mockDir, "tauri-plugin-autostart.ts"),
      "@tauri-apps/plugin-dialog": resolve(mockDir, "tauri-plugin-dialog.ts"),
      "@tauri-apps/plugin-updater": resolve(mockDir, "tauri-plugin-updater.ts"),
      "@tauri-apps/plugin-process": resolve(mockDir, "tauri-plugin-process.ts"),
      "@tauri-apps/plugin-fs": resolve(mockDir, "tauri-plugin-fs.ts"),
      "@tauri-apps/plugin-global-shortcut": resolve(mockDir, "tauri-plugin-global-shortcut.ts"),

      // ── Third-party Tauri plugins ─────────────────────────────────
      "tauri-plugin-macos-permissions-api": resolve(mockDir, "tauri-plugin-macos-perms.ts"),
    },
  },

  // Only build the main app entry point (skip overlay for E2E)
  build: {
    rollupOptions: {
      input: {
        main: resolve(root, "index.html"),
      },
    },
  },

  clearScreen: false,

  server: {
    port: 1420,
    strictPort: true,
    host: false,
    watch: {
      ignored: ["**/src-tauri/**"],
    },
  },
});
